### ISSUE TITLE
Will progressive sync controller support multi environment environment promotion?

### ISSUE THREAD

**Issue by surmabck** [Skyscanner/applicationset-progressive-sync#141]
Hi Team, you are doing awesome job here! 

I've opened this issue to ask you a question whether you are planning to support following environment promotion scenario:
App is running in multiple clusters per environment (let's say 2 dev, 2 preprod, 2 prod)
Once there is an update to the app that should be rolled into those clusters:
1. it is being rolled out into both dev clusters
2. [environment promotion] if app was rolled out successfully to both dev clusters then app will be rolled out into preprod clusters, otherwise whole pipeline fails and no sync will be done in preprod clusters
3. [environment promotion] same as 2 but from preprod to prod

**Comment by maruina** [comment]
Hey @surmabck sorry for the late reply but I missed the notification.

I think we will be able to support your use case out-of-the-box. Imagine that you have all your clusters in ArgoCD and you have labelled them with `env: dev`, `env: preprod` and `env: prod`.

Then if you write a ProgressiveSync similar to
```
apiVersion: argoproj.skyscanner.net/v1alpha1
kind: ProgressiveSync
metadata:
  name: myprogressiverollout
  namespace: argocd
spec:
  # a reference to the target ApplicationSet
  sourceRef:
    apiVersion: argoproj.io/v1alpha1
    kind: ApplicationSet
    name: myappset
    # the rollout steps
  stages:
      # human friendly name
    - name: two clusters in dev
      maxParallel: 2
      maxTargets: 2
      targets:
        clusters:
          selector:
            matchLabels:
              env: dev
    - name: two clusters in preprod
      maxParallel: 2
      maxTargets: 2
      targets:
        clusters:
          selector:
            matchLabels:
              env: preprod
    - name: two clusters in prod
      maxParallel: 1
      maxTargets: 2
      targets:
        clusters:
          selector:
            matchLabels:
              env: prod
 ```
 This will update the 2 dev clusters in parallel. If they are successful it will then move to the preprod ones and finally it will sync the 2 prod ones but one at the time. If any of the stage fails the ProgressiveSync will stop.
