### ISSUE TITLE
Sometimes stages executed in parallel

### ISSUE THREAD

**Issue by riuvshyn** [Skyscanner/applicationset-progressive-sync#147]
sometimes stages executed in parallel potentially due to some race condition

I've noticed this unexpected behaviour quite a couple times already when apps are going outOfSync due to git change and getting executed in parallel without staging. 

maybe this happens because status is not instantly getting updated due to k8s eventual consistency or in place where app sync is invoked or so...

ProgressiveSync ex:
```
apiVersion: argoproj.skyscanner.net/v1alpha1
kind: ProgressiveSync
metadata:
  labels:
    argocd.argoproj.io/instance: argocd-apps
  name: test
  namespace: argocd
spec:
  sourceRef:
    apiGroup: argoproj.io/v1alpha1
    kind: ApplicationSet
    name: test
  stages:
  - maxParallel: 1
    maxTargets: 100%
    name: finish rollout staging
    targets:
      clusters:
        selector:
          matchLabels:
            environment: staging
  - maxParallel: 1
    maxTargets: 100%
    name: finish rollout production
    targets:
      clusters:
        selector:
          matchLabels:
            environment: production
```
